version: '3'

services:
  server:
    image: alexandregv/onset-server:latest
    build: .
    restart: always
    #user: root # Uncomment this if you have problems with permissions
    environment:
      MYSQL_WAIT: ${MYSQL_WAIT-1}
      MYSQL_HOST: ${MYSQL_HOST-db}
      MYSQL_DATABASE: ${MYSQL_DATABASE-onset}
      MYSQL_USER: ${MYSQL_USER-onset}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD-onset}
    volumes:
     # Plugins and packages folders
      - ./plugins:/Steam/OnsetServer/plugins
      - ./packages:/Steam/OnsetServer/packages
     # Server config
      - ./server_config.json:/Steam/OnsetServer/server_config.json
      - ./weapons.json:/Steam/OnsetServer/weapons.json
     # Sandbox files
      - ./world.json:/Steam/OnsetServer/world.json
      - ./schematics.json:/Steam/OnsetServer/schematics.json
    ports:
      - '7777:7777/udp'
      - '7776:7776/udp'
      - '7775:7775/tcp'

  db:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_INITDB_SKIP_TZINFO: ${MYSQL_INIT_DB_SKIP_TZINFO-1}
      MYSQL_DATABASE: ${MYSQL_DATABASE-onset}
      MYSQL_USER: ${MYSQL_USER-onset}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD-onset}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD-onset}
    volumes:
       - db_data:/var/lib/mysql

volumes:
  db_data:
